/**
 * The Indian credit-card catalog, as plain data.
 *
 * This is deliberately NOT code that talks to Prisma. It's a list anyone (including a future
 * you, or an agent picking this up cold) can extend by adding entries, with no changes to the
 * seeding logic in prisma/seed.ts. "Every credit card in the Indian market" isn't a fixed
 * target: issuers reprice, discontinue, and launch products constantly, so treat this as a
 * living, ever-growing list rather than a one-time import.
 *
 * Ground rules for adding a card here (per the product's no-fabrication rule):
 * - Every CardProductSeed needs a `sourceNote` naming what was checked and when, and saying
 *   plainly that it's indicative and should be verified with the issuer.
 * - If a fact isn't confirmed (a fee, a redemption value, a base rate), leave the field
 *   `undefined` rather than guessing a plausible-looking number. `baseRewardRateOnCurrency`
 *   left unset means the reward engine treats this card as "no confirmed rate" rather than
 *   silently estimating zero as if that were a real answer.
 * - `categoryRules[].categoryName` must match a name in prisma/seed.ts's CATEGORIES or
 *   CARD_CATEGORIES lists (Food, Shopping, Transport, Entertainment, Bills, Health, Education,
 *   Other, Travel, Dining, Grocery, Fuel, Utilities). Use `null` for a channel-only rule (e.g.
 *   "5% online, 1% offline" cards) that isn't tied to a spend category at all.
 * - Multiple cards can share a RewardCurrencySeed by name (e.g. plain cashback is always
 *   worth Rs 1/unit regardless of issuer). Only give a card its own named currency when its
 *   redemption value genuinely differs from an existing one.
 */

export interface IssuerSeed {
  name: string;
  shortCode: string;
}

export interface RewardCurrencySeed {
  name: string;
  type: "POINTS" | "CASHBACK" | "MILES";
  unitValueInr: string;
  valueNote?: string;
}

export interface CardCategoryRuleSeed {
  categoryName: string | null;
  channel: "ANY" | "ONLINE" | "OFFLINE";
  multiplier: string;
  capAmount?: string;
  capPeriod?: "MONTHLY" | "ANNUAL";
  notes?: string;
}

export interface CardProductSeed {
  issuerName: string;
  name: string;
  slug: string;
  network: "VISA" | "MASTERCARD" | "RUPAY" | "AMEX" | "DINERS";
  variant?: string;
  joiningFee?: string;
  annualFee: string;
  annualFeeWaiverSpend?: string;
  rewardCurrencyName?: string;
  baseRewardRateOnCurrency?: string;
  foreignTxnFeePercent?: string;
  loungeAccessDomestic?: number;
  loungeAccessIntl?: number;
  milestoneNote?: string;
  benefitsNote?: string;
  exclusionsNote?: string;
  eligibilityNote?: string;
  sourceNote: string;
  categoryRules?: CardCategoryRuleSeed[];
}

export const ISSUERS: IssuerSeed[] = [
  { name: "HDFC Bank", shortCode: "HDFC" },
  { name: "Axis Bank", shortCode: "AXIS" },
  { name: "SBI Card", shortCode: "SBI" },
  { name: "American Express", shortCode: "AMEX" },
  { name: "ICICI Bank", shortCode: "ICICI" },
  { name: "RBL Bank", shortCode: "RBL" },
  { name: "IndusInd Bank", shortCode: "INDUSIND" },
  { name: "AU Small Finance Bank", shortCode: "AU" },
  { name: "Kotak Mahindra Bank", shortCode: "KOTAK" },
  { name: "HSBC", shortCode: "HSBC" },
  { name: "IDFC First Bank", shortCode: "IDFC" },
  { name: "Federal Bank", shortCode: "FEDERAL" },
  { name: "Bank of Baroda", shortCode: "BOB" },
  { name: "Yes Bank", shortCode: "YES" },
  { name: "Standard Chartered", shortCode: "SC" },
  { name: "Punjab National Bank", shortCode: "PNB" },
];

export const REWARD_CURRENCIES: RewardCurrencySeed[] = [
  {
    name: "HDFC Reward Points",
    type: "POINTS",
    unitValueInr: "0.5000",
    valueNote:
      "Redemption value ranges ~Rs 0.50 (flights/hotels) to ~Rs 0.65 (Gold Catalogue); Rs 0.50 used as the conservative default.",
  },
  {
    name: "Axis EDGE Miles",
    type: "MILES",
    unitValueInr: "1.0000",
    valueNote: "1 EDGE Mile = Rs 1 when redeemed via the Axis Travel EDGE portal.",
  },
  {
    name: "SBI Cashback",
    type: "CASHBACK",
    unitValueInr: "1.0000",
    valueNote: "Cashback currency is rupees; auto-credited to the card account.",
  },
  {
    name: "Amex Membership Rewards Points",
    type: "POINTS",
    unitValueInr: "0.3000",
    valueNote:
      "Approximate. Actual value varies significantly by transfer/redemption partner; not confirmed by current sources.",
  },
  {
    name: "HDFC CashPoints",
    type: "CASHBACK",
    unitValueInr: "0.2500",
    valueNote:
      "3,000 CashPoints/month cap is worth Rs 750, implying ~Rs 0.25/point; must be manually redeemed against the statement.",
  },
  {
    name: "Amazon Pay Balance",
    type: "CASHBACK",
    unitValueInr: "1.0000",
    valueNote: "Cashback is credited directly as Amazon Pay balance, so 1 unit = Rs 1.",
  },
  { name: "Axis ACE Cashback", type: "CASHBACK", unitValueInr: "1.0000" },
  { name: "Flipkart Axis Cashback", type: "CASHBACK", unitValueInr: "1.0000" },
  {
    name: "HDFC Infinia Reward Points",
    type: "POINTS",
    unitValueInr: "1.0000",
    valueNote:
      "~3.3% effective return via SmartBuy on flights/hotels implies ~Rs 1/point at this card's earn rate; varies by redemption.",
  },
  {
    name: "Axis Magnus Reward Points",
    type: "POINTS",
    unitValueInr: "0.5000",
    valueNote:
      "Not confirmed by current sources, Magnus's redemption value varies by tier and partner. Treat as a rough placeholder.",
  },
  {
    name: "RBL Rewards Points",
    type: "POINTS",
    unitValueInr: "0.2500",
    valueNote: "Not confirmed by current sources; treat as a rough placeholder.",
  },
  {
    name: "Avios",
    type: "MILES",
    unitValueInr: "0.5000",
    valueNote: "Not confirmed by current sources; British Airways Avios value varies widely by redemption route.",
  },
  {
    name: "AU LIT Points",
    type: "POINTS",
    unitValueInr: "0.2500",
    valueNote: "AU LIT's reward mechanics depend on user-selected packs; this value is a rough placeholder only.",
  },
  {
    name: "SBI Rewardz Points",
    type: "POINTS",
    unitValueInr: "0.2500",
    valueNote: "Not independently re-verified this session; treat as a rough placeholder.",
  },
  {
    name: "Kotak Reward Points",
    type: "POINTS",
    unitValueInr: "0.2500",
    valueNote: "Not independently re-verified this session; treat as a rough placeholder.",
  },
  { name: "HSBC Cashback", type: "CASHBACK", unitValueInr: "1.0000" },
  { name: "IndianOil Axis Cashback", type: "CASHBACK", unitValueInr: "1.0000" },
  {
    name: "IDFC First Reward Points",
    type: "POINTS",
    unitValueInr: "0.2500",
    valueNote: "Not independently re-verified this session; treat as a rough placeholder.",
  },
  {
    name: "Scapia Points",
    type: "POINTS",
    unitValueInr: "0.2500",
    valueNote: "Scapia's own currency is largely usable within its app for travel bookings; value outside that is unclear.",
  },
  {
    name: "IndusInd Reward Points",
    type: "POINTS",
    unitValueInr: "0.2500",
    valueNote: "Not confirmed by current sources; treat as a rough placeholder.",
  },
  { name: "Generic INR Cashback", type: "CASHBACK", unitValueInr: "1.0000" },
  {
    name: "HDFC Diners Reward Points",
    type: "POINTS",
    unitValueInr: "0.5000",
    valueNote: "10X SmartBuy redemptions can be worth more; Rs 0.50 used as the conservative flat-redemption default.",
  },
  {
    name: "Marriott Bonvoy Points",
    type: "POINTS",
    unitValueInr: "0.4000",
    valueNote: "Marriott's own typical valuation guidance is ~0.3-0.5 cents/point equivalent; not independently confirmed here.",
  },
  {
    name: "Yes Bank Reward Points",
    type: "POINTS",
    unitValueInr: "0.2500",
    valueNote: "Not confirmed by current sources; treat as a rough placeholder.",
  },
  {
    name: "Standard Chartered Reward Points",
    type: "POINTS",
    unitValueInr: "0.2500",
    valueNote: "Not confirmed by current sources; treat as a rough placeholder.",
  },
  {
    name: "HSBC Premier Points",
    type: "POINTS",
    unitValueInr: "0.5000",
    valueNote: "1:1 transfer to some airline partners suggests a higher value than entry-level cards; not independently confirmed.",
  },
  {
    name: "EaseMyTrip Points",
    type: "POINTS",
    unitValueInr: "1.0000",
    valueNote: "Redeemable within the EaseMyTrip travel portal; treated as roughly Rs 1/point for travel bookings there.",
  },
  {
    name: "ICICI Reward Points",
    type: "POINTS",
    unitValueInr: "0.2500",
    valueNote: "Not confirmed by current sources; treat as a rough placeholder.",
  },
  {
    name: "PNB Reward Points",
    type: "POINTS",
    unitValueInr: "0.2000",
    valueNote: "Not confirmed by current sources; treat as a rough placeholder.",
  },
  {
    name: "Kotak Mojo Points",
    type: "POINTS",
    unitValueInr: "0.2500",
    valueNote: "Not confirmed by current sources; treat as a rough placeholder.",
  },
];

export const CARD_PRODUCTS: CardProductSeed[] = [
  // ---------- Originally seeded flagship four ----------
  {
    issuerName: "HDFC Bank",
    name: "Regalia Gold",
    slug: "hdfc-regalia-gold",
    network: "VISA",
    joiningFee: "2500.00",
    annualFee: "2500.00",
    annualFeeWaiverSpend: "400000.00",
    rewardCurrencyName: "HDFC Reward Points",
    baseRewardRateOnCurrency: "2.667",
    milestoneNote: "Quarterly spend milestone voucher worth Rs 1,500 (up to Rs 10,000/year); exact spend threshold not confirmed.",
    benefitsNote:
      "Complimentary Swiggy One and MakeMyTrip Black Gold membership. 5X points at select partner brands (Myntra, Nykaa, Reliance Digital, Marks & Spencer). A merchant-specific boost, not modeled as a category rule.",
    exclusionsNote: "Lounge access benefit exists but exact visit count was not confirmed from current sources.",
    sourceNote: "Indicative only, checked 22 Aug 2026 against Paisabazaar and HDFC Bank's own fees page. Verify with HDFC before relying on this.",
  },
  {
    issuerName: "Axis Bank",
    name: "Atlas",
    slug: "axis-atlas",
    network: "VISA",
    annualFee: "5000.00",
    rewardCurrencyName: "Axis EDGE Miles",
    baseRewardRateOnCurrency: "2.000",
    milestoneNote: "2,500 EDGE Miles on reaching Rs 3,00,000 in annual spend. No annual-fee spend waiver.",
    benefitsNote: "2,500 EDGE Miles welcome bonus on first transaction. Redeemable across 20+ travel partners.",
    sourceNote: "Indicative only, checked 22 Aug 2026 against Paisabazaar and Axis Bank's own rewards page. Verify with Axis Bank before relying on this.",
    categoryRules: [{ categoryName: "Travel", channel: "ANY", multiplier: "2.50", notes: "Axis Travel EDGE portal, direct airline and direct hotel spends." }],
  },
  {
    issuerName: "SBI Card",
    name: "Cashback",
    slug: "sbi-cashback",
    network: "VISA",
    annualFee: "999.00",
    annualFeeWaiverSpend: "200000.00",
    rewardCurrencyName: "SBI Cashback",
    baseRewardRateOnCurrency: "1.000",
    benefitsNote: "1% fuel surcharge waiver (Rs 500-3,000 txns, max Rs 100/statement). Cashback auto-credited within 2 days of next statement.",
    sourceNote: "Indicative only, checked 22 Aug 2026 against Paisabazaar and RewardMatrix. Verify with SBI Card before relying on this.",
    categoryRules: [
      { categoryName: null, channel: "ONLINE", multiplier: "5.00", capAmount: "2000.00", capPeriod: "MONTHLY", notes: "5% online cashback, capped Rs 2,000/month combined with offline." },
      { categoryName: null, channel: "OFFLINE", multiplier: "1.00", capAmount: "2000.00", capPeriod: "MONTHLY", notes: "1% offline cashback, shares the Rs 2,000/month cap with online." },
    ],
  },
  {
    issuerName: "American Express",
    name: "Membership Rewards Credit Card",
    slug: "amex-mrcc",
    network: "AMEX",
    annualFee: "4500.00",
    annualFeeWaiverSpend: "150000.00",
    rewardCurrencyName: "Amex Membership Rewards Points",
    baseRewardRateOnCurrency: "2.000",
    benefitsNote: "1,000 bonus points for 4+ txns of Rs 1,500+/month, plus 1,000 more for Rs 20,000+ monthly spend. 50% fee waiver at Rs 90,000 spend, full at Rs 1,50,000.",
    exclusionsNote: "No rewards earned on fuel, insurance, utilities, or cash transactions.",
    sourceNote: "Indicative only, checked 22 Aug 2026 against RewardMatrix and CardInsider. Joining fee and MR redemption value not confirmed, left unset. Verify with Amex before relying on this.",
    categoryRules: [
      { categoryName: "Fuel", channel: "ANY", multiplier: "0.00", notes: "Fuel transactions earn no Membership Rewards points." },
      { categoryName: "Utilities", channel: "ANY", multiplier: "0.00", notes: "Utility bill payments earn no Membership Rewards points." },
    ],
  },

  // ---------- Second batch (Phase 4 catalog expansion) ----------
  {
    issuerName: "HDFC Bank",
    name: "Millennia",
    slug: "hdfc-millennia",
    network: "VISA",
    joiningFee: "1000.00",
    annualFee: "1000.00",
    annualFeeWaiverSpend: "100000.00",
    rewardCurrencyName: "HDFC CashPoints",
    baseRewardRateOnCurrency: "0.667",
    benefitsNote: "5% CashPoints on Amazon, Flipkart, Swiggy, Zomato, BookMyShow and other named partners (merchant-specific, not modeled as a category rule). Capped at 3,000 CashPoints (~Rs 750)/month.",
    sourceNote: "Indicative only, checked 22 Aug 2026 against Paisabazaar. Verify with HDFC before relying on this.",
  },
  {
    issuerName: "HDFC Bank",
    name: "Infinia",
    slug: "hdfc-infinia",
    network: "VISA",
    joiningFee: "12500.00",
    annualFee: "12500.00",
    annualFeeWaiverSpend: "1000000.00",
    rewardCurrencyName: "HDFC Infinia Reward Points",
    baseRewardRateOnCurrency: "3.333",
    benefitsNote: "Unlimited domestic lounge access, unlimited international via Priority Pass. ~3.3% effective SmartBuy return. From Apr 2026, retention needs Rs 18L annual spend or Rs 50L bank relationship value.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against Paisabazaar, HDFC Bank, CardExpert. Verify with HDFC before relying on this.",
  },
  {
    issuerName: "ICICI Bank",
    name: "Amazon Pay",
    slug: "icici-amazon-pay",
    network: "VISA",
    joiningFee: "0.00",
    annualFee: "0.00",
    rewardCurrencyName: "Amazon Pay Balance",
    baseRewardRateOnCurrency: "1.000",
    benefitsNote: "5% cashback on Amazon.in for Prime members, 3% for non-Prime, 2% on partner merchants (merchant-specific, not modeled as a category rule). Lifetime free.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against Paisabazaar, OnePaisa, MyMoneyMantra. Verify with ICICI Bank before relying on this.",
  },
  {
    issuerName: "Axis Bank",
    name: "ACE",
    slug: "axis-ace",
    network: "VISA",
    joiningFee: "499.00",
    annualFee: "499.00",
    annualFeeWaiverSpend: "200000.00",
    rewardCurrencyName: "Axis ACE Cashback",
    baseRewardRateOnCurrency: "1.500",
    benefitsNote: "5% cashback on Google Pay bill payments and 4% on Swiggy/Zomato/Ola (app/merchant-specific, not modeled as a category rule), combined cap ~Rs 500/month. 1.5% uncapped on everything else.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against MyMoneyMantra and GrabOn (rates vary slightly by source). Verify with Axis Bank before relying on this.",
  },
  {
    issuerName: "Axis Bank",
    name: "Magnus",
    slug: "axis-magnus",
    network: "VISA",
    joiningFee: "12500.00",
    annualFee: "12500.00",
    annualFeeWaiverSpend: "2500000.00",
    rewardCurrencyName: "Axis Magnus Reward Points",
    baseRewardRateOnCurrency: "6.000",
    benefitsNote: "Unlimited domestic and international lounge access via Priority Pass. Reward rate is spend-tiered (higher multipliers unlock at Rs 1.5L+ monthly spend, and further on the Travel EDGE portal). Shown rate is base tier only.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against Paisabazaar and CardInsider. Verify with Axis Bank before relying on this.",
  },
  {
    issuerName: "Axis Bank",
    name: "Flipkart",
    slug: "axis-flipkart",
    network: "VISA",
    joiningFee: "500.00",
    annualFee: "500.00",
    annualFeeWaiverSpend: "350000.00",
    rewardCurrencyName: "Flipkart Axis Cashback",
    baseRewardRateOnCurrency: "1.500",
    benefitsNote: "7.5% cashback on Myntra, 5% on Flipkart, 4% on preferred partners (merchant-specific, not modeled as a category rule), capped ~Rs 4,000/quarter per merchant. 1.5% on everything else.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against MyMoneyMantra. Verify with Axis Bank before relying on this.",
  },
  {
    issuerName: "SBI Card",
    name: "SimplyCLICK",
    slug: "sbi-simplyclick",
    network: "VISA",
    joiningFee: "499.00",
    annualFee: "499.00",
    annualFeeWaiverSpend: "100000.00",
    rewardCurrencyName: "SBI Rewardz Points",
    baseRewardRateOnCurrency: "1.250",
    benefitsNote: "2.5% on select online partners (Amazon, BookMyShow, Cleartrip and others. Merchant-specific, not modeled as a category rule). 1.25% on all other online spending.",
    sourceNote: "Indicative only, checked 25 Aug 2026 against Paisabazaar. Verify with SBI Card before relying on this.",
  },
  {
    issuerName: "SBI Card",
    name: "Elite",
    slug: "sbi-elite",
    network: "VISA",
    joiningFee: "4999.00",
    annualFee: "4999.00",
    annualFeeWaiverSpend: "1000000.00",
    rewardCurrencyName: "SBI Rewardz Points",
    baseRewardRateOnCurrency: "2.000",
    benefitsNote: "5x reward points on dining, grocery, and departmental store spends.",
    sourceNote: "Indicative only, fee and rates not independently re-verified this session. Based on prior research and general market knowledge. Verify with SBI Card before relying on this.",
    categoryRules: [
      { categoryName: "Dining", channel: "ANY", multiplier: "5.00", notes: "5x reward points on dining spends." },
      { categoryName: "Grocery", channel: "ANY", multiplier: "5.00", notes: "5x reward points on grocery and departmental store spends." },
    ],
  },
  {
    issuerName: "IDFC First Bank",
    name: "Millennia",
    slug: "idfc-first-millennia",
    network: "VISA",
    joiningFee: "0.00",
    annualFee: "0.00",
    rewardCurrencyName: "IDFC First Reward Points",
    baseRewardRateOnCurrency: "1.000",
    benefitsNote: "4 complimentary railway lounge visits per quarter. Lifetime free.",
    sourceNote: "Indicative only, checked 25 Aug 2026 against Paisabazaar and Stable Money. Verify with IDFC First Bank before relying on this.",
    categoryRules: [{ categoryName: null, channel: "ONLINE", multiplier: "3.00", capAmount: "20000.00", capPeriod: "MONTHLY", notes: "3x points on online spends, capped at Rs 20,000 of qualifying spend/month." }],
  },
  {
    issuerName: "RBL Bank",
    name: "World Safari",
    slug: "rbl-world-safari",
    network: "VISA",
    joiningFee: "3000.00",
    annualFee: "3000.00",
    rewardCurrencyName: "RBL Rewards Points",
    baseRewardRateOnCurrency: "2.000",
    milestoneNote: "10,000 bonus points on reaching Rs 2.5 lakh in annual spend (per research); verify current terms.",
    benefitsNote: "Complimentary airport lounge access, zero forex markup, fuel surcharge waiver.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against Stable Money. Annual fee is a commonly cited figure, not independently re-verified. Verify with RBL Bank before relying on this.",
    categoryRules: [{ categoryName: "Travel", channel: "ANY", multiplier: "2.50", notes: "Travel-related purchases." }],
  },
  {
    issuerName: "IndusInd Bank",
    name: "Legend (Avios)",
    slug: "indusind-legend-avios",
    network: "VISA",
    joiningFee: "10000.00",
    annualFee: "10000.00",
    rewardCurrencyName: "Avios",
    benefitsNote: "Earns British Airways Avios directly. Premium travel positioning.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against Paisabazaar and TravelDiari. Base earn rate not confirmed, intentionally left unset. Verify with IndusInd Bank before relying on this.",
  },
  {
    issuerName: "AU Small Finance Bank",
    name: "LIT",
    slug: "au-lit",
    network: "VISA",
    joiningFee: "499.00",
    annualFee: "499.00",
    annualFeeWaiverSpend: "100000.00",
    rewardCurrencyName: "AU LIT Points",
    benefitsNote: "Customizable reward packs (cashback/travel/dining/fuel) chosen in the AU 0101 app. Reward mechanic depends on selected pack, so a single base rate is intentionally left unset.",
    sourceNote: "Indicative only, fee not independently re-verified this session. Verify with AU Small Finance Bank before relying on this.",
  },
  {
    issuerName: "Kotak Mahindra Bank",
    name: "League Platinum",
    slug: "kotak-league-platinum",
    network: "VISA",
    joiningFee: "500.00",
    annualFee: "500.00",
    annualFeeWaiverSpend: "100000.00",
    rewardCurrencyName: "Kotak Reward Points",
    baseRewardRateOnCurrency: "1.333",
    sourceNote: "Indicative only, fee and rate not independently re-verified this session. Verify with Kotak Mahindra Bank before relying on this.",
  },
  {
    issuerName: "HSBC",
    name: "Live+",
    slug: "hsbc-live-plus",
    network: "MASTERCARD",
    joiningFee: "999.00",
    annualFee: "999.00",
    annualFeeWaiverSpend: "200000.00",
    rewardCurrencyName: "HSBC Cashback",
    baseRewardRateOnCurrency: "1.500",
    sourceNote: "Indicative only, checked 26 Aug 2026 against general market knowledge and MyMoneyMantra. Verify with HSBC before relying on this.",
    categoryRules: [
      { categoryName: "Dining", channel: "ANY", multiplier: "6.67", capAmount: "1000.00", capPeriod: "MONTHLY", notes: "10% cashback on dining and food delivery, including via UPI, capped Rs 1,000/month combined with grocery." },
      { categoryName: "Grocery", channel: "ANY", multiplier: "6.67", capAmount: "1000.00", capPeriod: "MONTHLY", notes: "10% cashback on grocery spends, capped Rs 1,000/month combined with dining." },
    ],
  },
  {
    issuerName: "Axis Bank",
    name: "IndianOil",
    slug: "indianoil-axis",
    network: "RUPAY",
    joiningFee: "500.00",
    annualFee: "500.00",
    annualFeeWaiverSpend: "50000.00",
    rewardCurrencyName: "IndianOil Axis Cashback",
    baseRewardRateOnCurrency: "1.000",
    benefitsNote: "Fuel-focused co-branded card; value-back is redeemable at IndianOil outlets.",
    sourceNote: "Indicative only, fee and rate not independently re-verified this session. Verify with Axis Bank/IndianOil before relying on this.",
    categoryRules: [{ categoryName: "Fuel", channel: "ANY", multiplier: "5.00", capAmount: "250.00", capPeriod: "MONTHLY", notes: "5% value-back on fuel at IndianOil outlets, capped at an estimated Rs 250/month." }],
  },

  // ---------- Third batch (this expansion round) ----------
  {
    issuerName: "Federal Bank",
    name: "Scapia",
    slug: "federal-scapia",
    network: "VISA",
    joiningFee: "0.00",
    annualFee: "0.00",
    rewardCurrencyName: "Scapia Points",
    baseRewardRateOnCurrency: "2.000",
    benefitsNote: "10% back on bookings made via the Scapia app, 2% on other spends. 4 domestic lounge visits/quarter (Rs 10,000 spend trigger). Lifetime free, no forex markup.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against CardExpert and CreditSmart. Verify with Federal Bank/Scapia before relying on this.",
  },
  {
    issuerName: "IndusInd Bank",
    name: "Tiger",
    slug: "indusind-tiger",
    network: "VISA",
    joiningFee: "0.00",
    annualFee: "0.00",
    rewardCurrencyName: "IndusInd Reward Points",
    baseRewardRateOnCurrency: "1.000",
    benefitsNote: "1-6 points per Rs 100 depending on spend category (tiered structure not fully confirmed). 8 domestic + 2 international lounge visits annually. Lifetime free.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against CardExpert. Category tiering not confirmed in detail. Base rate shown is the low end. Verify with IndusInd Bank before relying on this.",
  },
  {
    issuerName: "HDFC Bank",
    name: "Swiggy",
    slug: "hdfc-swiggy-blck",
    network: "VISA",
    variant: "BLCK",
    joiningFee: "1000.00",
    annualFee: "1000.00",
    annualFeeWaiverSpend: "200000.00",
    rewardCurrencyName: "HDFC CashPoints",
    baseRewardRateOnCurrency: "5.000",
    benefitsNote: "10% cashback on Swiggy (food delivery, Instamart, Dineout), 5% on other online spends. Merchant-specific, not modeled as a category rule.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against CardExpert and MyMoneyMantra. Verify with HDFC Bank before relying on this.",
  },
  {
    issuerName: "Bank of Baroda",
    name: "Eterna",
    slug: "bob-eterna",
    network: "VISA",
    joiningFee: "0.00",
    annualFee: "0.00",
    rewardCurrencyName: "Generic INR Cashback",
    baseRewardRateOnCurrency: "1.000",
    benefitsNote: "Up to 3.75% cashback on online spends (merchant/category structure not fully confirmed). Lifetime free for a limited period per issuer terms.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against CardExpert. Fee waiver terms unclear. Treated as free pending confirmation. Verify with Bank of Baroda before relying on this.",
  },
  {
    issuerName: "HDFC Bank",
    name: "Tata Neu Infinity",
    slug: "hdfc-tata-neu-infinity",
    network: "RUPAY",
    joiningFee: "1499.00",
    annualFee: "1499.00",
    annualFeeWaiverSpend: "300000.00",
    rewardCurrencyName: "Generic INR Cashback",
    baseRewardRateOnCurrency: "1.500",
    benefitsNote: "5% NeuCoins on UPI/utility/insurance spends via the Tata Neu app. Merchant/app-specific, not modeled as a category rule. RuPay network enables UPI-linked spending.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against CardExpert. Fee is a commonly cited figure, not independently re-verified. Verify with HDFC Bank before relying on this.",
  },
  {
    issuerName: "American Express",
    name: "Reserve",
    slug: "amex-reserve",
    network: "AMEX",
    annualFee: "10000.00",
    rewardCurrencyName: "Amex Membership Rewards Points",
    baseRewardRateOnCurrency: "4.000",
    benefitsNote: "~2% return (in MR points) on spends up to Rs 50,000/month. Accor Plus membership included.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against CardExpert. Joining fee not confirmed, left unset. Verify with American Express before relying on this.",
  },
  {
    issuerName: "HDFC Bank",
    name: "Marriott Bonvoy",
    slug: "hdfc-marriott-bonvoy",
    network: "VISA",
    joiningFee: "3000.00",
    annualFee: "3000.00",
    rewardCurrencyName: "Marriott Bonvoy Points",
    baseRewardRateOnCurrency: "3.333",
    benefitsNote: "8 Bonvoy points per Rs 150 on Marriott stays (merchant-specific, not modeled as a category rule). 12 lounge visits/year via DreamFolks.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against CreditSmart. Verify with HDFC Bank before relying on this.",
  },
  {
    issuerName: "Yes Bank",
    name: "Marquee",
    slug: "yes-bank-marquee",
    network: "VISA",
    joiningFee: "9999.00",
    annualFee: "4999.00",
    annualFeeWaiverSpend: "1000000.00",
    rewardCurrencyName: "Yes Bank Reward Points",
    baseRewardRateOnCurrency: "1.000",
    benefitsNote: "Unlimited international lounge visits, 24 domestic lounge visits/year for primary and add-on members.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against Paisabazaar and BankBazaar. Base reward rate not confirmed by current sources; a conservative placeholder is used. Verify with Yes Bank before relying on this.",
  },
  {
    issuerName: "Standard Chartered",
    name: "Ultimate",
    slug: "sc-ultimate",
    network: "MASTERCARD",
    annualFee: "5000.00",
    rewardCurrencyName: "Standard Chartered Reward Points",
    baseRewardRateOnCurrency: "3.300",
    benefitsNote: "3.3% reward rate on all spends (flat rate, no category rule needed) with shopping voucher redemptions.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against CardExpert. Fee not independently re-verified. Verify with Standard Chartered before relying on this.",
  },
  {
    issuerName: "HSBC",
    name: "Premier",
    slug: "hsbc-premier",
    network: "MASTERCARD",
    variant: "Metal",
    annualFee: "20000.00",
    rewardCurrencyName: "HSBC Premier Points",
    benefitsNote: "1:1 points transfer to airline partners, accelerated travel rewards. Requires HSBC Premier banking relationship. Eligibility is relationship-based, not purely spend-based.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against CardExpert. Fee is an estimate for the standalone card product; actual eligibility ties to banking relationship tier. Base reward rate not confirmed, left unset. Verify with HSBC before relying on this.",
  },
  {
    issuerName: "ICICI Bank",
    name: "Emeralde Private Metal",
    slug: "icici-emeralde-private-metal",
    network: "VISA",
    joiningFee: "12499.00",
    annualFee: "12499.00",
    annualFeeWaiverSpend: "1000000.00",
    rewardCurrencyName: "EaseMyTrip Points",
    baseRewardRateOnCurrency: "6.000",
    benefitsNote: "Unlimited lounge access via Priority Pass + DragonPass. Rewards redeemable via EaseMyTrip travel portal.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against RewardMatrix. Verify with ICICI Bank before relying on this.",
  },
  {
    issuerName: "Axis Bank",
    name: "Airtel",
    slug: "axis-airtel",
    network: "VISA",
    annualFee: "500.00",
    annualFeeWaiverSpend: "200000.00",
    rewardCurrencyName: "Generic INR Cashback",
    baseRewardRateOnCurrency: "1.000",
    benefitsNote: "25% cashback on Airtel bills/recharges, 10% on utilities. Merchant-specific, not modeled as a category rule. Cap is dynamic and linked to base spend per issuer terms.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against MyMoneyMantra. Verify with Axis Bank before relying on this.",
  },
  {
    issuerName: "HDFC Bank",
    name: "MoneyBack+",
    slug: "hdfc-moneyback-plus",
    network: "VISA",
    joiningFee: "500.00",
    annualFee: "500.00",
    annualFeeWaiverSpend: "50000.00",
    rewardCurrencyName: "HDFC CashPoints",
    baseRewardRateOnCurrency: "1.333",
    benefitsNote: "10X CashPoints on select partner merchants, 5X on EMI transactions. Merchant/transaction-type specific, not modeled as a category rule.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against MyMoneyMantra. Verify with HDFC Bank before relying on this.",
  },
  {
    issuerName: "HSBC",
    name: "Cashback",
    slug: "hsbc-rupay-cashback",
    network: "RUPAY",
    annualFee: "499.00",
    annualFeeWaiverSpend: "200000.00",
    rewardCurrencyName: "HSBC Cashback",
    baseRewardRateOnCurrency: "1.000",
    sourceNote: "Indicative only, checked 26 Aug 2026 against MyMoneyMantra. Verify with HSBC before relying on this.",
    categoryRules: [
      { categoryName: "Dining", channel: "ANY", multiplier: "10.00", notes: "10% cashback on dining, food delivery and grocery." },
      { categoryName: "Grocery", channel: "ANY", multiplier: "10.00", notes: "10% cashback on dining, food delivery and grocery." },
    ],
  },
  {
    issuerName: "Bank of Baroda",
    name: "Cashback",
    slug: "bobcard-cashback",
    network: "VISA",
    annualFee: "588.00",
    annualFeeWaiverSpend: "100000.00",
    rewardCurrencyName: "Generic INR Cashback",
    baseRewardRateOnCurrency: "1.000",
    benefitsNote: "5% cashback on online spends, 1% on other spends. Billed as Rs 49/month rather than a single annual fee; the amount here is the yearly equivalent.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against MyMoneyMantra. Verify with Bank of Baroda before relying on this.",
    categoryRules: [{ categoryName: null, channel: "ONLINE", multiplier: "5.00", notes: "5% cashback on online spends." }],
  },
  {
    issuerName: "HDFC Bank",
    name: "Diners Club Black",
    slug: "hdfc-diners-club-black",
    network: "DINERS",
    joiningFee: "10000.00",
    annualFee: "10000.00",
    rewardCurrencyName: "HDFC Diners Reward Points",
    baseRewardRateOnCurrency: "2.667",
    benefitsNote: "Up to 10X points via SmartBuy on selected bookings. Unlimited domestic and international lounge access.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against RewardMatrix/CreditSmart. Verify with HDFC Bank before relying on this.",
  },
  {
    issuerName: "HDFC Bank",
    name: "Diners Club Privilege",
    slug: "hdfc-diners-club-privilege",
    network: "DINERS",
    joiningFee: "1000.00",
    annualFee: "1000.00",
    annualFeeWaiverSpend: "300000.00",
    rewardCurrencyName: "HDFC Diners Reward Points",
    baseRewardRateOnCurrency: "2.667",
    benefitsNote: "5X points on Swiggy and Zomato, up to 10X via SmartBuy. Merchant-specific, not modeled as a category rule.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against Paisabazaar. Verify with HDFC Bank before relying on this.",
  },
  {
    issuerName: "IDFC First Bank",
    name: "WOW!",
    slug: "idfc-first-wow",
    network: "VISA",
    joiningFee: "0.00",
    annualFee: "0.00",
    rewardCurrencyName: "IDFC First Reward Points",
    baseRewardRateOnCurrency: "1.500",
    eligibilityNote: "Secured card backed by a fixed deposit. No separate income proof required, but requires opening an FD with IDFC First Bank.",
    benefitsNote: "4X points on online spends (merchant/channel structure not fully confirmed).",
    sourceNote: "Indicative only, checked 26 Aug 2026 against CreditSmart. Verify with IDFC First Bank before relying on this.",
  },
  {
    issuerName: "RBL Bank",
    name: "IndianOil XTRA",
    slug: "rbl-indianoil-xtra",
    network: "VISA",
    annualFee: "1500.00",
    rewardCurrencyName: "IndianOil Axis Cashback",
    baseRewardRateOnCurrency: "1.000",
    benefitsNote: "Up to 8.5% value-back on fuel spends at IndianOil outlets per issuer marketing; exact tiering not confirmed.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against FreeFuelBill and CardMaven roundups. Verify with RBL Bank before relying on this.",
    categoryRules: [{ categoryName: "Fuel", channel: "ANY", multiplier: "8.50", notes: "Up to 8.5% value-back on IndianOil fuel purchases per issuer marketing." }],
  },
  {
    issuerName: "SBI Card",
    name: "BPCL Octane",
    slug: "sbi-bpcl-octane",
    network: "VISA",
    joiningFee: "1499.00",
    annualFee: "1499.00",
    annualFeeWaiverSpend: "200000.00",
    rewardCurrencyName: "SBI Rewardz Points",
    baseRewardRateOnCurrency: "1.000",
    benefitsNote: "Up to 7.25% value-back as reward points on BPCL fuel spends. 4 complimentary lounge visits/year with no spend condition.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against CardMaven and FreeFuelBill roundups. Verify with SBI Card before relying on this.",
    categoryRules: [{ categoryName: "Fuel", channel: "ANY", multiplier: "7.25", notes: "Up to 7.25% value-back on BPCL fuel purchases per issuer marketing." }],
  },
  {
    issuerName: "Bank of Baroda",
    name: "HPCL Energie",
    slug: "bob-hpcl-energie",
    network: "RUPAY",
    annualFee: "500.00",
    rewardCurrencyName: "Generic INR Cashback",
    baseRewardRateOnCurrency: "1.000",
    benefitsNote: "24 reward points per Rs 150 (up to 5% value-back) on HPCL fuel and LPG via the HP Pay app, plus 1% fuel surcharge waiver.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against CardMaven roundup. Verify with Bank of Baroda before relying on this.",
    categoryRules: [{ categoryName: "Fuel", channel: "ANY", multiplier: "5.00", notes: "Up to 5% value-back on HPCL fuel and LPG purchases per issuer marketing." }],
  },
  {
    issuerName: "HDFC Bank",
    name: "IndianOil",
    slug: "hdfc-indianoil",
    network: "VISA",
    annualFee: "500.00",
    annualFeeWaiverSpend: "50000.00",
    rewardCurrencyName: "Generic INR Cashback",
    baseRewardRateOnCurrency: "1.000",
    benefitsNote: "5% fuel points at IndianOil pumps; also earns on movies, grocery, dining and departmental store spends per issuer marketing (not itemized here).",
    sourceNote: "Indicative only, checked 26 Aug 2026 against FreeFuelBill roundup. Verify with HDFC Bank before relying on this. Distinct product from the Axis Bank IndianOil co-brand also in this catalog.",
    categoryRules: [{ categoryName: "Fuel", channel: "ANY", multiplier: "5.00", notes: "5% fuel points at IndianOil pumps." }],
  },
  {
    issuerName: "Yes Bank",
    name: "Prosperity Rewards Plus",
    slug: "yes-bank-prosperity-rewards-plus",
    network: "VISA",
    annualFee: "399.00",
    rewardCurrencyName: "Yes Bank Reward Points",
    baseRewardRateOnCurrency: "1.000",
    sourceNote: "Indicative only, checked 26 Aug 2026 against Paisabazaar and BankBazaar. Verify with Yes Bank before relying on this.",
  },
  {
    issuerName: "Bank of Baroda",
    name: "Select",
    slug: "bob-select",
    network: "VISA",
    joiningFee: "0.00",
    annualFee: "0.00",
    annualFeeWaiverSpend: "25000.00",
    rewardCurrencyName: "Generic INR Cashback",
    baseRewardRateOnCurrency: "0.667",
    benefitsNote: "10 reward points per Rs 100 on grocery, departmental stores, and movies; 4 points per Rs 100 on other spends.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against BankBazaar. Verify with Bank of Baroda before relying on this.",
    categoryRules: [
      { categoryName: "Grocery", channel: "ANY", multiplier: "15.00", notes: "10 points/Rs100 vs ~0.67 points/Rs100 base." },
      { categoryName: "Entertainment", channel: "ANY", multiplier: "15.00", notes: "Movies: 10 points/Rs100 vs ~0.67 points/Rs100 base." },
    ],
  },
  {
    issuerName: "Punjab National Bank",
    name: "RuPay Millennial",
    slug: "pnb-rupay-millennial",
    network: "RUPAY",
    joiningFee: "399.00",
    annualFee: "999.00",
    annualFeeWaiverSpend: "100000.00",
    rewardCurrencyName: "PNB Reward Points",
    baseRewardRateOnCurrency: "1.000",
    sourceNote: "Indicative only, checked 26 Aug 2026 against BankBazaar. Verify with Punjab National Bank before relying on this.",
  },
  {
    issuerName: "Punjab National Bank",
    name: "Visa Signature",
    slug: "pnb-visa-signature",
    network: "VISA",
    joiningFee: "1500.00",
    annualFee: "500.00",
    rewardCurrencyName: "PNB Reward Points",
    baseRewardRateOnCurrency: "1.000",
    sourceNote: "Indicative only, checked 26 Aug 2026 against BankBazaar. Verify with Punjab National Bank before relying on this.",
  },
  {
    issuerName: "ICICI Bank",
    name: "Coral",
    slug: "icici-coral",
    network: "VISA",
    annualFee: "500.00",
    rewardCurrencyName: "ICICI Reward Points",
    baseRewardRateOnCurrency: "2.000",
    sourceNote: "Indicative only, checked 26 Aug 2026 against StableMoney and Paisabazaar. Verify with ICICI Bank before relying on this.",
  },
  {
    issuerName: "ICICI Bank",
    name: "Sapphiro",
    slug: "icici-sapphiro",
    network: "VISA",
    joiningFee: "6500.00",
    annualFee: "3500.00",
    rewardCurrencyName: "ICICI Reward Points",
    baseRewardRateOnCurrency: "2.000",
    foreignTxnFeePercent: "3.50",
    benefitsNote: "4 points/Rs100 on international spends (2x domestic base rate), 1 point/Rs100 on utility and insurance spends.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against Paisabazaar. Verify with ICICI Bank before relying on this.",
    categoryRules: [
      { categoryName: "Utilities", channel: "ANY", multiplier: "0.50", notes: "1 point/Rs100 vs 2 points/Rs100 domestic base. Reduced, not accelerated, on utility spends." },
    ],
  },

  // ---------- Fourth batch (this expansion round) ----------
  {
    issuerName: "HDFC Bank",
    name: "Freedom",
    slug: "hdfc-freedom",
    network: "VISA",
    annualFee: "500.00",
    rewardCurrencyName: "HDFC CashPoints",
    baseRewardRateOnCurrency: "1.000",
    benefitsNote: "10X CashPoints on BigBasket, BookMyShow, OYO, Swiggy and Uber. Merchant-specific, not modeled as a category rule.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against Paisabazaar. Verify with HDFC Bank before relying on this.",
  },
  {
    issuerName: "SBI Card",
    name: "SimplySAVE",
    slug: "sbi-simplysave-rupay",
    variant: "RuPay",
    network: "RUPAY",
    annualFee: "0.00",
    rewardCurrencyName: "SBI Rewardz Points",
    baseRewardRateOnCurrency: "1.000",
    benefitsNote: "10x reward points on dining, departmental stores, and groceries.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against StableMoney. The regular (non-RuPay) SimplySAVE card may carry a different fee. This entry is specifically the RuPay variant. Verify with SBI Card before relying on this.",
    categoryRules: [
      { categoryName: "Dining", channel: "ANY", multiplier: "10.00", notes: "10x reward points on dining spends." },
      { categoryName: "Grocery", channel: "ANY", multiplier: "10.00", notes: "10x reward points on grocery and departmental store spends." },
    ],
  },
  {
    issuerName: "ICICI Bank",
    name: "Rubyx",
    slug: "icici-rubyx",
    network: "VISA",
    joiningFee: "5000.00",
    annualFee: "5000.00",
    rewardCurrencyName: "ICICI Reward Points",
    benefitsNote: "Milestone-based rewards: 3,000 points at Rs 3 lakh annual spend, plus 1,500 points per additional Rs 1 lakh, capped at 15,000 points/year. Complimentary lounge access and golf privileges. Base per-transaction reward rate (outside the milestone) was not confirmed by current sources and is intentionally left unset.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against StableMoney and ICICI Bank. Renewal fee assumed equal to joining fee, not independently confirmed as distinct. Verify with ICICI Bank before relying on this.",
  },
  {
    issuerName: "Kotak Mahindra Bank",
    name: "811",
    slug: "kotak-811",
    network: "VISA",
    annualFee: "0.00",
    rewardCurrencyName: "Kotak Mojo Points",
    baseRewardRateOnCurrency: "1.000",
    benefitsNote: "2.5 Mojo points per Rs 100 on online spends (a channel-wide boost, modeled as a CardCategoryRule below); 1 point per Rs 100 on other spends.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against CardInsider. Fee assumed lifetime-free based on this card's entry-level positioning, not independently confirmed. Verify with Kotak Mahindra Bank before relying on this.",
    categoryRules: [
      { categoryName: null, channel: "ONLINE", multiplier: "2.50", notes: "2.5 Mojo points per Rs 100 on online spends." },
    ],
  },
  {
    issuerName: "Kotak Mahindra Bank",
    name: "White",
    slug: "kotak-white",
    network: "VISA",
    joiningFee: "3000.00",
    annualFee: "3000.00",
    annualFeeWaiverSpend: "500000.00",
    benefitsNote: "Earns \"White Pass\" value at spend milestones, up to Rs 27,000/year. A milestone mechanic rather than a per-transaction reward rate, so no reward currency or base rate is modeled here. Includes fuel surcharge waiver.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against Paisabazaar and Kotak Mahindra Bank. Verify with Kotak Mahindra Bank before relying on this.",
  },
  {
    issuerName: "RBL Bank",
    name: "ShopRite",
    slug: "rbl-shoprite",
    network: "VISA",
    annualFee: "500.00",
    annualFeeWaiverSpend: "150000.00",
    rewardCurrencyName: "RBL Rewards Points",
    baseRewardRateOnCurrency: "1.000",
    sourceNote: "Indicative only, checked 26 Aug 2026 against Paisabazaar and StableMoney. Verify with RBL Bank before relying on this.",
    categoryRules: [
      { categoryName: "Grocery", channel: "ANY", multiplier: "20.00", capAmount: "250.00", capPeriod: "MONTHLY", notes: "20 reward points per Rs 100 on grocery, capped at 1,000 points (~Rs 250) per month." },
    ],
  },
  {
    issuerName: "RBL Bank",
    name: "Cookies",
    slug: "rbl-cookies",
    network: "VISA",
    annualFee: "499.00",
    rewardCurrencyName: "RBL Rewards Points",
    baseRewardRateOnCurrency: "1.000",
    benefitsNote: "5x reward points on eligible online spends (a channel-wide boost, modeled as a CardCategoryRule below), plus a 10% discount on BookMyShow, Zomato, Myntra and Uber (merchant-specific, not modeled as a category rule).",
    sourceNote: "Indicative only, checked 26 Aug 2026 against CardInsider. Verify with RBL Bank before relying on this.",
    categoryRules: [
      { categoryName: null, channel: "ONLINE", multiplier: "5.00", notes: "5x reward points on eligible online spends." },
    ],
  },
  {
    issuerName: "Axis Bank",
    name: "Neo",
    slug: "axis-neo",
    network: "VISA",
    joiningFee: "250.00",
    annualFee: "250.00",
    benefitsNote: "Direct discounts on everyday brands. Entry-level card; per-transaction reward rate not confirmed by current sources and intentionally left unset.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against Upstox and MyMoneyMantra. Verify with Axis Bank before relying on this.",
  },
  {
    issuerName: "Axis Bank",
    name: "SuperMoney",
    slug: "axis-supermoney-rupay",
    variant: "RuPay",
    network: "RUPAY",
    annualFee: "0.00",
    benefitsNote: "Lifetime free RuPay card. Reward structure not confirmed by current sources and intentionally left unset.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against Upstox. Verify with Axis Bank before relying on this.",
  },
  {
    issuerName: "Axis Bank",
    name: "Freecharge",
    slug: "axis-freecharge",
    network: "VISA",
    joiningFee: "250.00",
    annualFee: "250.00",
    benefitsNote: "Co-branded with Freecharge. Per-transaction reward rate not confirmed by current sources and intentionally left unset.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against Upstox. Verify with Axis Bank before relying on this.",
  },
  {
    issuerName: "IndusInd Bank",
    name: "EazyDiner",
    slug: "indusind-eazydiner",
    network: "VISA",
    joiningFee: "1999.00",
    annualFee: "1999.00",
    benefitsNote: "Dining-focused co-branded card with EazyDiner. Per-transaction reward rate not confirmed by current sources and intentionally left unset.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against StableMoney. Verify with IndusInd Bank before relying on this.",
  },
  {
    issuerName: "IndusInd Bank",
    name: "Platinum",
    slug: "indusind-platinum",
    network: "VISA",
    annualFee: "0.00",
    benefitsNote: "Lifetime free entry-level card. Reward structure not confirmed by current sources and intentionally left unset.",
    sourceNote: "Indicative only, checked 26 Aug 2026 against StableMoney. Verify with IndusInd Bank before relying on this.",
  },
];
